import { type ReqResTemplate, type WS } from '../types.ts';
import { rooms, usersDatabase, players } from '../database/database.ts';
import { eventType } from '../types.ts';

export function createRoom(data: ReqResTemplate, wsConnection: WS): void {
    // console.log('create!!!!!!!!!!!');
    const user = usersDatabase[usersDatabase.length - 1];

    if (user) {
        // Создаем новую комнату и добавляем пользователя в нее
        if (players.length === 1) {
            const newRoom = {
                id: rooms.length + 1,
                user1: {
                    name: user.name,
                    index: user.index,
                },
            };

            rooms.push(newRoom);

            // const resData = {
            //     idGame: newRoom.id,
            //     idPlayer: user.index,
            // };

            const resData = [
                {
                    roomId: newRoom.id,
                    roomUsers: [
                        {
                            name: newRoom.user1.name,
                            index: newRoom.user1.index,
                        },
                    ],
                },
            ];

            const resalt = {
                type: eventType.updateRoom,
                data: JSON.stringify(resData),
                id: 0,
            };

            wsConnection.send(JSON.stringify(resalt));
        } else {
            const resData = [
                {
                    roomId: rooms[rooms.length - 1].id,
                    roomUsers: [
                        {
                            name: rooms[0].user1?.name,
                            index: rooms[0].user1?.index,
                        },
                    ],
                },
            ];

            const resalt = {
                type: eventType.updateRoom,
                data: JSON.stringify(resData),
                id: 0,
            };

            wsConnection.send(JSON.stringify(resalt));
        }

        // if (players.length === 1) {
        //     const resData = {
        //         idGame: <number | string>,
        //         idPlayer: <number | string>, /* generated by server id for player in the game session, not enemy (unique id for every player) */
        //     },

        //     const resalt = {
        //         type: eventType.createGame,
        //         data: JSON.stringify(resData),
        //         id: 0,
        //     };

        //     wsConnection.send(JSON.stringify(resalt));
        // }
        // return response;
    } else {
        const resData = {
            error: true,
            errorText: 'Users not found in the database',
        };

        const resalt = {
            type: eventType.updateRoom,
            data: JSON.stringify(resData),
            id: 0,
        };

        // return errorResponse;
        wsConnection.send(JSON.stringify(resalt));
    }

    // console.log('cr rm', data);
    // const resData = [
    //     {
    //         roomId: 1,
    //         roomUsers: [{}],
    //     },
    // ];
    // const resalt = {
    //     type: 'update_room',
    //     data: JSON.stringify(resData),
    //     id: 0,
    // };
    // if (rooms.length === 0) {
    //     rooms.push({ id: rooms.length + 1 });
    //     // console.log(resalt);
    //     return resalt;
    // } else {
    //     for (let i = 0; i < rooms.length; i++) {
    //         const key = Object.keys(rooms[i]);
    //         console.log('key', key);
    //         if (!('user1' in rooms[i]) && 'user2' in rooms[i]) {
    //             console.log('user2!!!!!!!!!11');
    //             resData[0].roomId = rooms[i].id;
    //             const userInRoom = {
    //                 name: rooms[i].user2?.name,
    //                 index: rooms[i].user2?.index,
    //             };
    //             resData[0].roomUsers.splice(0, 1, userInRoom);
    //             return resalt;
    //             // resData[0].roomUsers.push(userInRoom);
    //         } else if ('user1' in rooms[i] && !('user2' in rooms[i])) {
    //             console.log('user1!!!!!!!!!11');
    //             resData[0].roomId = rooms[i].id;
    //             const userInRoom = {
    //                 name: rooms[i].user1?.name,
    //                 index: rooms[i].user1?.index,
    //             };
    //             resData[0].roomUsers.splice(0, 1, userInRoom);
    //             return resalt;
    //             // resData[0].roomUsers.push(userInRoom);
    //         } else {
    //             // console.log('000000');
    //             // const newRoomIndex = rooms.length + 1;
    //             // rooms.push({ id: newRoomIndex });
    //             // resData[0].roomId = rooms.length;
    //             // return resalt;
    //         }
    //     }
    //     console.log('craete room update', resalt);
    //     return resalt;
    // }
}

// export function createRoom(data: ReqResTemplate, wsConnection?: WS): ReqResTemplate {
//     console.log('wsConnection', wsConnection?._socket?._server._connections);

//     const resData = [
//         {
//             roomId: 1,
//             roomUsers: [{}],
//         },
//     ];
//     const resalt = {
//         type: 'update_room',
//         data: JSON.stringify(resData),
//         id: 0,
//     };

//     return resalt;
// }
